# https://medium.com/@mpaternostro/how-to-deploy-pages-on-github-using-actions-a9281d03b345

name: Doxygen

# Controls when the workflow will run
on:
  # Generate regularly
  schedule:
   - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gen_doxygen:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Setup - CMake
        uses: lukka/get-cmake@latest

      - name: Setup - System
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install doxygen graphviz
          # Cleanup (we want to avoid wasting disk space)
          sudo apt-get clean

      - name: Checkout
        run: |
          git clone https://github.com/BRL-CAD/brlcad.git

      - name: Directory setup
        run: |
          cmake -E make_directory ./build_doxygen
          cmake -E make_directory $HOME/.cache
          cmake -E make_directory $HOME/.cache/BRL-CAD

      - name: Configure
        run: |
          export PATH=$ENV{GITHUB_WORKSPACE}:$PATH
          cmake -S ./brlcad -G Ninja -B build_doxygen -DBRLCAD_DOXYGEN_ONLY=ON -DCMAKE_BUILD_TYPE=Release -DBRLCAD_EXT_PARALLEL=1

      - name: Build
        run: |
          export PATH=$ENV{GITHUB_WORKSPACE}:$PATH
          cmake --build build_doxygen --config Release --target doxygen

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          # location of the coverage artifacts
          path: "./build_doxygen/doc/doxygen_output/html"

  upload_doxygen:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: gen_doxygen

    permissions:
      pages: write
      id-token: write

    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

